@startuml PatientProfileDelete(level1)

actor "Admin" as Admin
participant HealthCareSystem as "HealthCareSystem" <<system (C4)>>

activate Admin
    
    Admin -> HealthCareSystem : asks to delete a patient profile
    activate HealthCareSystem

    HealthCareSystem --> Admin : asks to confirm
    deactivate HealthCareSystem

    Admin -> HealthCareSystem : corfirms
    activate HealthCareSystem 
    
    HealthCareSystem --> Admin: shows success message
    deactivate HealthCareSystem
    
deactivate Admin


@enduml