@startuml
actor Admin as "Admin"
participant SYS as "HealthCare System" <<system (C4)>>

activate Admin 

Admin --> SYS : asks to delete specializations 

activate SYS 
SYS --> Admin : shows confirmation message
deactivate SYS


@enduml
