@startuml

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system>>
participant DB as "Database"


Admin -> BE : GET /api/operationTypes/search{filters}
activate BE

BE -> DB : getOperationTypeBy(name,specialization,status)

activate DB 

DB -> BE : operation types 

deactivate DB

Admin <- BE : 200 OK (operationTypes)

deactivate BE

@enduml