@startuml

actor Doctor as "Doctor"
participant SYS as "HealthCare System" <<system>>

activate Doctor 

Doctor --> SYS : Request an Operation 

activate SYS 

SYS --> Doctor : confirms the operation  has been requested successfully


@enduml