@startuml

skinparam packageStyle rectangle

package JobOpeningAggregate {
 entity JobOpening <<root>> <<entity>>{
 description
 }

 class JobReference <<Value>> {
 }

 class NumberOfVacancies <<Value>> {
 }

 class ContractType<<Value>> {
 }

 class WorkRegime <<Value>>{
 }

 class JobTitle <<Value>> {
 }
 }





'CustomerManagerAggregate
package CustomerManagerAggregate{
entity CustomerManager<<entity>> <<root>> { }
}

'CompanyAggregate
package CompanyAggregate {
entity Company <<entity>> <<root>>{
}

class CompanyName <<Value>>{}

class CompanyAddress <<Value>>{}

}

'JobOpening
JobOpening "1" --> "1" JobTitle : contains
JobOpening "1" --> "1" ContractType
JobOpening "1" --> "1" WorkRegime : contains
JobOpening "1" --> "1" NumberOfVacancies : has
JobOpening "1" --> "1"  JobReference
JobOpening "1" --> "1" Company



'Company
CustomerManager "1" -> "0..*"JobOpening : creates
CustomerEmployee "1" --> "1..*" Company :   belongs to
Company "1" --> "1" CompanyName : has
Company "1" --> "1" CompanyAddress : is located


@enduml