@startuml

actor BackofficeUser as "Backoffice User"
participant SYS as "Backoffice System" <<system (C4)>>

activate BackofficeUser

BackofficeUser --> SYS : request reset password

activate SYS

SYS --> BackofficeUser : return reset password condirmation

deactivate SYS
deactivate BackofficeUser
@enduml