@startuml

actor Admin as "Admin"
participant SYS as "HealthCare System" <<system>>

activate Admin 

Admin --> SYS : asks to edit an staff

activate SYS 

SYS --> Admin : confirms the staff edit was successfull


@enduml