@startuml

actor Admin as "Admin"
participant SYS as "HealthCare System" <<system>>

activate Admin 

opt want to filter
    Admin -> SYS : asks to search staffs by (fullName / specializationId /\n phoneNumber / Email)
    activate SYS
    SYS --> Admin : return staff profile
    deactivate SYS
end

Admin -> SYS : asks to edit a staff profile
activate SYS 

SYS --> Admin : confirms the staff profile editing was successfull

@enduml