@startuml 
autonumber
actor Doctor as "Doctor"
participant CTRL as "OperationRequestController"
participant SERVICE as "OperationRequestService <<service>>"

database IOperationRepository as "IOperationRepository"



activate Doctor

Doctor -> CTRL : DELETE /{id}/delete
activate CTRL

CTRL -> SERVICE : deleteAsync(OperationId)
activate SERVICE

SERVICE -> IOperationRepository : remove(operationId)

activate IOperationRepository

IOperationRepository-> SERVICE : operationRequest

deactivate IOperationRepository


SERVICE -> IOperationRepository : addAsync(OperationRequest)
activate IOperationRepository
IOperationRepository -> SERVICE : operationRequest
deactivate IOperationRepository


alt OwnerShipValidated = 0 

SERVICE -> IOperationRepository : getDoctorOwnerShip (doctorID)

activate IOperationRepository 

IOperationRepository -> SERVICE : OwnerShipValidated

deactivate IOperationRepository

SERVICE -> CTRL : BussinessErrorException

CTRL -> Doctor : 406 Not Aceptable
end alt 

SERVICE -> IOperationRepository : getDoctorOwnerShip (doctorID)

activate IOperationRepository 

IOperationRepository -> SERVICE : OwnerShipValidated

deactivate IOperationRepository
SERVICE -> IOperationRepository : remove(operationId) 

activate IOperationRepository 

IOperationRepository -> SERVICE : operationRequest
deactivate IOperationRepository

SERVICE -> CTRL : operation

deactivate SERVICE 

CTRL -> Doctor : 200 OK

deactivate CTRL 

deactivate Doctor
@enduml