@startuml

autonumber
Actor Doctor as "Doctor"
participant BE as "Backend Management" <<system>>
participant DB as "Database"

Doctor-> BE : DELETE /{id}/delete
activate BE

BE -> DB : deleteAsync(id)

activate DB 

DB -> BE : operationRequest 

deactivate DB 

BE -> DB : confirms doctor ownership

activate DB

DB -> BE : operationRequest.doctorId

deactivate DB

deactivate DB 

Doctor <- BE : 200 Deleted

deactivate BE

@enduml