@startuml

actor Admin as "Admin"
participant SYS as "Backoffice System" <<system (C4)>>

activate Admin

Admin -> SYS : Create new staff profile (input details)
activate SYS

SYS -> SYS : Validate input ( first name, last name, contact information, specialization)
SYS -> SYS : Generate unique Staff ID (License Number)
SYS -> SYS : Save profile

SYS -> Admin : Confirm profile created

deactivate SYS
deactivate Admin
@enduml