@startuml

skinparam packageStyle rectangle


'InterviewModelAggregate
package InterviewModelAggregate {
entity InterviewModel<<root>> <<entity>> {
}

class InterviewModelType <<Value>>{}
}


'InterviewAggregate
package InterviewAggregate {

  entity Interview <<root>> <<entity>>{

  }

  class InterviewForms <<Value>> {

  }

  class InterviewDate <<Value>> {

  }

  class Score <<Value>> {
  }
}

  'ValidationServiceAggregate
  package ValidationService {
     entity ANTLRValidator <<service>> {
     }
  }

   'RankingServiceAggregate
    package RankingService {
    entity Ranking <<service>> {
    }
    }


Interview "1" --> "1" Score : generates
Interview "1" --> "1" InterviewForms
Interview "1" --> "1" InterviewDate

InterviewModel "1" --> "1" InterviewModelType : has
Interview "1" --> "1" InterviewModel : follows

ANTLRValidator --> Interview : validates

Ranking --> Interview : ranks

@enduml