@startuml

entity InterviewModel<<root>> <<entity>> {

}

class InterviewModelPlugin <<Value>>{}

 entity Interview <<root>> <<entity>>{

  }

  class InterviewForms <<Value>> {

  }

  class InterviewDate <<Value>> {

  }

  class Score <<Value>> {
  }

  'Interview
  Interview "1" --> "1" Score : generates
  Interview "1" --> "1" InterviewForms
  Interview "1" --> "1" InterviewDate

  'InterviewModel
  InterviewModel "1" --> "1" InterviewModelPlugin : has
  Interview "1" --> "1" InterviewModel : follows
@enduml