@startuml 
autonumber
actor Admin as "Admin"
participant CTRL as "OperationTypesController"
participant SERVICE as "OperationTypeService <<service>>"
participant OperationType as "OperationType <<domain>>"
participant OperationTypeDTO as "OperationTypeDTO <<domain>>"
participant OperationTypeSpecialization as "OperationTypeSpecialization <<domain>>"
database IOperationTypeRepository as "IOperationTypeRepository"
database SpecializationRepository as "SpecializationRepository"
database IOperationTypeSpecializationRepository as "IOperationTypeSpecializationRepository"

activate Admin

Admin -> CTRL : POST /api/operationTypes
activate CTRL

CTRL -> SERVICE : addAsync(creatingOperationTypeDTO)
activate SERVICE

SERVICE -> OperationType : create(creatingOperationTypeDTO.name,creatingOperationTypeDTO.estimatedDuration,creatingOperationTypeDTO.anesthesiaTime,creatingOperationTypeDTO.surgeryTime,creatingOperationTypeDTO.cleaningTime)

activate OperationType

OperationType -> SERVICE : operationType

deactivate OperationType

SERVICE -> IOperationTypeRepository : addAsync(operationType)

activate IOperationTypeRepository

IOperationTypeRepository -> SERVICE : operationType

deactivate IOperationTypeRepository

loop forEach specialization 

SERVICE -> SpecializationRepository : getByIdAsync (specializationId)

activate SpecializationRepository 

SpecializationRepository -> SERVICE : specialization

deactivate SpecializationRepository

alt specialization != null 

SERVICE -> OperationTypeSpecialization : create(operationTypeId,SpecializationId,numberOfStaff)

activate OperationTypeSpecialization 

OperationTypeSpecialization -> SERVICE : operationTypeSpecialization

deactivate OperationTypeSpecialization

SERVICE -> IOperationTypeSpecializationRepository : addAsync(operationTypeSpecialization)

else 

SERVICE -> CTRL : NotFoundException

CTRL -> Admin : 404 Not Found

end alt 
end loop

SERVICE -> OperationTypeDTO : create(operationTypeId,name,anesthesiaTime,surgeryTime,cleaningTime)

activate OperationTypeDTO

OperationTypeDTO -> SERVICE : operationTypeDTO

deactivate OperationTypeDTO

SERVICE -> CTRL : operationTypeDTO

deactivate SERVICE 

CTRL -> Admin : 201 Created

deactivate CTRL 

deactivate Admin
@enduml