@startuml PatientProfileCreation(level3-1)

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system (C4)>>
participant DB as "Database"

Admin-> BE : POST /api/patients
activate BE

    BE -> DB : Store new patient profile
    activate DB
    DB --> BE : Profile stored
    deactivate DB
    BE -> Admin : 201 Patient profile created
deactivate BE

@enduml