@startuml 
autonumber
actor Admin as "Admin"
participant CTRL as "OperationTypesController"
participant SERVICE as "OperationTypeService <<service>>"
participant OperationTypeDTO as "OperationTypeDTO <<domain>>"
database IOperationTypeRepository as "IOperationTypeRepository"
database OperationTypeSpecializationRepositorie as "OperationTypeSpecializationRepositorie <<repositorie>>"


activate Admin

Admin -> CTRL : POST /api/operationTypes{id}
activate CTRL

CTRL -> SERVICE : editAsync(editOperationTypeDTO)
activate SERVICE



deactivate IOperationTypeRepository

SERVICE -> IOperationTypeRepository : editAsync(editOperationTypeDTO.name,editOperationTypeDTO.estimatedDuration)

activate IOperationTypeRepository

IOperationTypeRepository -> SERVICE : operationType

deactivate IOperationTypeRepository

SERVICE -> OperationTypeSpecializationRepositorie : edit(operationTypeId,SpecializationId,numberOfStaff)

activate OperationTypeSpecializationRepositorie 

OperationTypeSpecializationRepositorie -> SERVICE : operationTypeSpecialization

deactivate OperationTypeSpecializationRepositorie



SERVICE -> CTRL : operationType

deactivate SERVICE 

CTRL -> Admin : 200 OK

deactivate CTRL 

deactivate Admin
@enduml