@startuml

actor Admin as "Admin"
participant SYS as "HealthCare System" <<system>>

activate Admin 

Admin -> SYS : Requests to search for staff profiles by \n eg. name, specialization,  or email.

activate SYS 

SYS --> Admin : Lists staff profiles.


@enduml