@startuml Patient Profile Update (level 2)

autonumber
actor Admin as "Admin"
participant SYS as "Backend Management" <<system (C4)>>

activate Admin
Admin -> SYS : POST /api/patients
activate SYS

SYS -> SYS : updatePatientProfile(updatingPatientProfileDTO)
SYS --> Admin : 201 Updated
deactivate SYS


@enduml