@startuml Patient Profile Delete (level 2)

autonumber
actor Admin as "Admin"
participant SYS as "Healthcare System" <<system (C4)>>

activate Admin

Admin-> SYS : DELETE /api/patients
activate SYS

SYS -> SYS : deletePatientProfile(medicalRecordNumber)
SYS--> Admin : 201 Deleted
deactivate SYS

@enduml