@startuml PatientProfileDelete(level2)

autonumber
actor Admin as "Admin"
participant SYS as "Healthcare System" <<system (C4)>>

activate Admin

Admin-> SYS : DELETE api/patients/{id}/hard
activate SYS

SYS -> SYS : deletePatientProfile(medicalRecordNumber)
SYS--> Admin : 200 Deleted
deactivate SYS

@enduml