@startuml PatientProfileUpdate(level3-1)

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system>>
participant DB as "Database"

Admin -> BE : PUT /api/patients/{id}
activate BE

BE -> DB : update patient

activate DB 

DB --> BE : patientProfileUpdated 

deactivate DB 

BE --> Admin : 200 Updated

deactivate BE

@enduml