@startuml

autonumber
actor Admin as "Admin"
participant SYS as "Backend Management" <<system>>



Admin -> SYS : GET /api/operationTypes/search{filters}
activate SYS

SYS -> SYS : searchOperationTypes(name,specialization,status)
Admin <-- SYS : 200 Ok
deactivate SYS


@enduml