@startuml

entity Interview <<root>> <<entity>>{

  }

  class InterviewForms <<Value>> {

  }

  class InterviewDate <<Value>> {

  }

  class Score <<Value>> {
  }

  entity CustomerManager<<entity>> <<root>> { }

  class InterviewModelPlugin{
  }


Interview "1" --> "1" Score : generates
Interview "1" --> "1" InterviewForms
Interview "1" --> "1" InterviewDate
CustomerManager "1" --> "1.." InterviewForms : uploads
InterviewModelPlugin --> InterviewForms : validates
@enduml
