@startuml
title Select Job Requirements Class Diagram

class SelectJobRequirementsUI {
    + doShow() : boolean
    + headline() : String
    + showMenuAndGetSelection() : JobOpening
}

class SelectJobRequirementsController {
    +listAllJobOpenings(): Iterable<JobOpening>
    +selectJobRequirementsToJobOpening(jobReference: String, pluginName: String): void
}

class PersistenceContext {
    +create(): void
}

class RepositoryFactory {
    +factory(): void
    +jobOpenings(): JobOpeningRepository
    +interviewModels(): JobRequirementsRepository
}

class JobReference {
    +create(jobReference : String, code : CustomerCode, serialNumber : Integer ): void
}

class RequirementsSpecification {
    +create(jobReference: JobReference, pluginName: String): void
}

class JobOpeningRepository {
 + findAllOpen() : Iterable<JobOpening>
}

class JobRequirementsRepository {
   + save(model : InterviewModel)
}

SelectJobRequirementsUI --> SelectJobRequirementsController : theController
SelectJobRequirementsController --> PersistenceContext : persistence
PersistenceContext --> RepositoryFactory : factory
RepositoryFactory --> JobOpeningRepository : jobOpeningRepository
RepositoryFactory --> JobRequirementsRepository : JobRequirementsRepository
SelectJobRequirementsController --> JobReference : create
SelectJobRequirementsController --> RequirementsSpecification : create
@enduml
