@startuml
title Select Interview Model Class Diagram

class SelectInterviewModelUI {
    + doShow() : boolean
    + headline() : String
    + showMenuAndGetSelection() : JobOpening
}

class SelectInterviewModelController {
    +listAllJobOpenings(): Iterable<JobOpening>
    +selectInterviewModelToInterview(jobReference: String, pluginName: String): void
}

class PersistenceContext {
    +create(): void
}

class RepositoryFactory {
    +factory(): void
    +jobOpenings(): JobOpeningRepository
    +interviewModels(): InterviewModelRepository
}

class JobReference {
    +create(jobReference : String, code : CustomerCode, serialNumber : Integer ): void
}

class InterviewModel {
    +create(jobReference: JobReference, pluginName: String): void
}

class JobOpeningRepository {
 + findAllOpen() : Iterable<JobOpening>
}

class InterviewModelRepository {
   + save(model : InterviewModel)
}

SelectInterviewModelUI --> SelectInterviewModelController : theController
SelectInterviewModelController --> PersistenceContext : persistence
PersistenceContext --> RepositoryFactory : factory
RepositoryFactory --> JobOpeningRepository : jobOpeningRepository
RepositoryFactory --> InterviewModelRepository : interviewModelRepository
SelectInterviewModelController --> JobReference : create
SelectInterviewModelController --> InterviewModel : create
@enduml
