@startuml process-view
autonumber

actor "Doctor" as Doctor
participant Frontend as "Frontend" <<system (C4)>>
participant BackendManagement as "BackendManagement" <<system (C4)>>

activate Doctor
    Doctor -> Frontend : asks to remove operation requisition
    activate Frontend
        Frontend --> Doctor : asks to confirm
    deactivate Frontend
    Doctor -> Frontend : confirms
    activate Frontend
        Frontend-> BackendManagement : DELETE /operationRequests/{id}
        activate BackendManagement
            Frontend <-- BackendManagement : 200 OK
        deactivate BackendManagement
    Frontend --> Doctor : shows success message
    deactivate Frontend
deactivate Doctor

@enduml