@startuml Patient Profile Creation (level 2)

autonumber
participant SYS as "Healthcare System" <<system (C4)>>

?o-> SYS : POST /api/users/patient
activate SYS

SYS -> SYS : createPatientProfile(patientProfileDTO)
<-- SYS : 201 Created
deactivate SYS

@enduml