@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor CustomerManager as Actor
participant DisplayCandidateInfoUI as UI <<presentation>>
participant DisplayCandidateInfoController as Controller <<application>>
participant AuthorizationService as AuthzService<<service>>
participant CandidateService as CandidateService<<service>>
participant "candidate:Candidate" as Domain <<domain>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database CandidateRepository as Repository <<repository>>

Actor --> UI: Display all the personal data of a candidate
activate Actor
activate UI

UI --> Actor : Ask candidate email
Actor --> UI : email

    UI -> Controller: create
                activate Controller

                Controller --> AuthzService : ensureAuthenticatedUserHasAnyOf(Jobs4uRoles.POWER_USER,Jobs4uRoles.CUSTOMER_MANAGER)
                deactivate AuthzService

                Controller --> CandidateService : findByEmail(email)
                activate CandidateService

                CandidateService --> Persistence : repositories()

                Persistence --> Factory : create()

                Persistence --> CandidateService : factory
                deactivate Persistence

                CandidateService --> Factory : candidates()
                activate Factory

                Factory --> Repository : create()

                Factory --> CandidateService : candidateRepository
                deactivate Factory

                CandidateService --> Repository : findByEmail(email)
                activate Repository

                Repository --> CandidateService : candidate
                deactivate Repository

                CandidateService --> Controller : candidate
                deactivate CandidateService
                activate Controller

                Controller --> UI : candidate
                deactivate Controller

    UI--> Actor : display all the personal data of candidate

deactivate UI
deactivate Actor

@enduml