@startuml

entity JobRequirements <<root>> <<entity>>{

  }

  class JobRequirementsData <<Value>> {

  }

  entity Operator<<entity>> <<root>> { }

  class JobRequirementsPlugin{
  }

JobRequirements "1" --> "1" JobRequirementsData
Operator "1" --> "1.." JobRequirementsData : uploads
JobRequirementsPlugin --> JobRequirementsData : validates
@enduml
