@startuml

package JobOpeningAggregate {
  entity JobOpening <<root>> <<entity>>{
    description
  }

  class JobReference <<Value>> {}
  class NumberOfVacancies <<Value>> {}
  class ContractType<<Value>> {}
  class WorkRegime <<Value>>{}
  class JobTitle <<Value>> {}
}

package InterviewModelAggregate {
  entity InterviewModel<<root>> <<entity>> {}
  class InterviewModelPlugin <<Value>>{}
}

package ApplicationAggregate {
  entity Application<<entity>> <<root>>  {}
  class ApplicationDate <<Value>> {}
  enum ApplicationStatus <<Value>> {
    Approved
    Denied
    WaitingInterview
    InProgress
  }
}

package CustomerManagerAggregate{
  entity CustomerManager<<entity>> <<root>> { }
}

package InterviewAggregate {
  class Interview <<entity>><<root>>{}
  class Score<<value>>{}
  class JustificationText<<value>>{}
  class InterviewDate<<value>>{}
  class InterviewTime<<value>>{}
}

 package ValidationService {
    entity ANTLRValidator <<service>> {
    }
 }

Interview "1" --> "1" Score : generates
Interview "1" --> "1" JustificationText
Interview "1" --> "1" InterviewDate
Interview "1" --> "1" InterviewTime

InterviewModel "1" --> "1" InterviewModelPlugin : has
Interview "1" --> "1" InterviewModel : follows

ANTLRValidator --> Interview : validates

JobOpening "1" --> "1" JobTitle
JobOpening "1" --> "1" ContractType
JobOpening "1" --> "1" WorkRegime
JobOpening "1" --> "1" NumberOfVacancies
JobOpening "1" --> "1" JobReference

Application "1" --> "1" ApplicationDate
Application "1" --> "1" Interview
Application "1" --> "1" ApplicationStatus
Application "1" --> "1" JobOpening : has

CustomerManager --> Interview : evaluates


 @enduml