@startuml

package NotificationsAggregate{
  class Notification <<entity>>{
    title
    content
  }
  class Date<<value>>{}
  enum NotificationStatus<<value>>{
    READ
    UNREAD
  }
}

package CandidateAggregate{
  entity Candidate <<entity>> <<root>> {}
  class PhoneNumber<<Value>>{}
}

package ApplicationAggregate {
  entity Application<<entity>> <<root>>  {}
  class ApplicationDate <<Value>> {}
  enum ApplicationStatus <<Value>> {
    Approved
    Denied
    WaitingInterview
    InProgress
  }
}

Candidate --> Notification : receives

Notification "1" --> "1" Application : for
Notification "1" --> "1" Date : has
Notification "1" --> "1" NotificationStatus : has

Application "1" --> "1" ApplicationDate
Application "1" --> "1" ApplicationStatus
Application "1" --> "1" Candidate : belongs to


@enduml