@startuml PatientProfileUpdate(level2)

autonumber
actor Admin as "Admin"
participant SYS as "Backend Management" <<system (C4)>>

activate Admin
Admin -> SYS : PUT /api/patients/{id}
activate SYS

SYS -> SYS : updatePatientProfile(editingPatientDTO)
SYS --> Admin : 200 Updated
deactivate SYS


@enduml