@startuml

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system>>
participant DB as "Database"

Admin-> BE : POST: api/staffs
activate BE

BE -> DB : addAsync(creatingStaffDTO)



activate DB 

DB -> DB : confirms User ID

DB -> DB : confirms User specialization

DB -> DB : save staff

activate DB 

DB -> BE : staff 

deactivate DB 

Admin <- BE : 201 Created

deactivate BE

@enduml