@startuml 
autonumber
actor Admin as "Admin"
participant CTRL as "StaffsController"
participant SERVICE as "StaffService <<service>>"
database UserRepository as "UserRepository"
database SpecializationRepository as "SpecializationRepository"
database IOperationRequestRepository as "IStaffRepository"

activate Admin

Admin -> CTRL : POST /api/staffs
activate CTRL

CTRL -> SERVICE : addAsync(creatingStaffDTO)
activate SERVICE

alt userValidated = 0 

SERVICE -> UserRepository : GetByIdAsync(new Username(creatingStaffDTO.UserId))

activate UserRepository 

UserRepository -> SERVICE : userValidated

deactivate UserRepository

SERVICE -> CTRL : ValueErrorException

CTRL -> Admin : 406 Not Aceptable
end alt 

alt specializationValidated = 0 

SERVICE -> SpecializationRepository : GetByIdAsync(new SpecializationId(creatingStaffDTO.SpecializationId))

activate SpecializationRepository 

SpecializationRepository -> SERVICE : specializationValidated

deactivate SpecializationRepository

SERVICE -> CTRL : ValueErrorException

CTRL -> Admin : 406 Not Aceptable
end alt 

SERVICE -> UserRepository :  GetByIdAsync(new Username(creatingStaffDTO.UserId))

activate UserRepository 

UserRepository -> SERVICE : userValidated

deactivate UserRepository

SERVICE -> SpecializationRepository : GetByIdAsync(new SpecializationId(creatingStaffDTO.SpecializationId))

activate SpecializationRepository 

SpecializationRepository -> SERVICE : specializationValidated

deactivate SpecializationRepository
SERVICE -> IOperationRequestRepository : addAsync(creatingStaffDTO.FistName,creatingStaffDTO.LastName,creatingStaffDTO.FullName,\n creatingStaffDTO.LicenseNumber, creatingStaffDTO.SpecializationId, creatingStaffDTO.Email,\ncreatingStaffDTO.PhoneNumber, creatingStaffDTO.StaffAvailabilitySlots,creatingStaffDTO.UserId)

activate IOperationRequestRepository 

IOperationRequestRepository -> SERVICE : staff
deactivate IOperationRequestRepository


SERVICE -> CTRL : staffDTO

deactivate SERVICE 

CTRL -> Admin : 201 Created

deactivate CTRL 

deactivate Admin
@enduml