@startuml

actor Admin as "Admin"
participant SYS as "Backoffice System" <<system (C4)>>

activate Admin 
Admin -> SYS : asks to register for the healthcare system
activate SYS 
SYS --> Admin : confirms the registration

deactivate SYS
deactivate Admin
@enduml