@startuml process-view
autonumber
skinparam DefaultTextAlignment center

actor Admin as "Admin"
participant ComponentUI as "UI Component" <<component (C4)>>
participant Component as "Component" <<component (C4)>>
participant Model as "Model" <<component (C4)>>
participant Service as "Service" <<component (C4)>>
participant HTTP as "HTTP" <<component (C4)>>

participant CTRL as "SpecializationsController" <<component (C4)>>
participant SpecializationService as "SpecializationService" <<component (C4)>>
participant SpecializationRepo as "SpecializationRepo" <<persistence>>
participant Specialization as "Specialization" <<domain>>
activate Admin

    Admin -> ComponentUI : asks to update one specialization
    activate ComponentUI

        ComponentUI --> Admin : asks to update data
    
    deactivate ComponentUI

    Admin -> ComponentUI : update data

    activate ComponentUI

        ComponentUI -> Component : update Specialization
        activate Component

            Component -> Model** : create

            Component -> Service : update Specialization
            activate Service

                Service -> HTTP : put('/specializations/{id}')

                activate HTTP
                    HTTP -> CTRL : PUT /specializations/{id}
                    activate CTRL

                    CTRL -> SpecializationService : updateAsync(specializationDto)
                    
                    activate SpecializationService 

                    SpecializationService -> SpecializationRepo : getByIdAsync(specializationDto.id)

                    activate SpecializationRepo 

                    SpecializationRepo --> SpecializationService : specialization

                    deactivate SpecializationRepo

                    SpecializationService -> Specialization : ChangeSpecializationName(specializationDto.name)

                    SpecializationService -> SpecializationRepo : save(specialization)

                    activate SpecializationRepo 

                    SpecializationRepo --> SpecializationService : specialization

                    deactivate SpecializationRepo

                    SpecializationService -> SpecializationService : toDto(specialization)

                    SpecializationService --> CTRL : specializationDto
                    deactivate SpecializationService

                    CTRL --> HTTP : 200 (specializationDto)

                    deactivate CTRL
                                        
                    HTTP --> Service : specializationDto

                deactivate HTTP

                Service --> Component : specializationDto
            deactivate Service

            Component --> ComponentUI : specializationDto
        deactivate Component

    Admin <-- ComponentUI : shows updated data
    deactivate ComponentUI

deactivate Admin

@enduml