@startuml Patient Profile Update (level 3 - 2)

autonumber
actor Admin as "Admin"
participant CTRL as "PatientsController"
participant SERVICE as "PatientService <<service>>"
participant PATIENT as "Patient <<domain>>"
participant REPO as "Patient Repository"
participant DTO as "updatingPatientProfileDTO : PatientProfileDTO"

Admin-> CTRL : PUT /api/patients
activate CTRL

CTRL -> SERVICE : createPatientProfileAsync(creatingPatientProfileDTO)
activate SERVICE

    SERVICE -> PATIENT : update(updatingPatientProfileDTO.firstName, updatingPatientProfileDTO.lastName, updatingPatientProfileDTO.fullName, updatingPatientProfileDTO.medicalHistory, updatingPatientProfileDTO.allergies)
    activate PATIENT

    PATIENT -> SERVICE : patientUpdated
    deactivate PATIENT

    SERVICE -> REPO : save(patientUpdated)
    activate USERREPO

    REPO -> SERVICE : patientUpdated
    deactivate REPO
    activate DTO
    
    SERVICE -> DTO : update(updatingPatientProfileDTO.fullName, updatingPatientProfileDTO.medicalHistory, updatingPatientProfileDTO.allergies)
    
    DTO -> SERVICE : patientProfileDto
    deactivate DTO

    SERVICE -> CTRL : patientProfileDto
    
    <-- CTRL : 201 Patient Profile Updated

deactivate SERVICE
deactivate CTRL
@enduml
