@startuml process-view
autonumber

actor "Admin" as Admin
participant Frontend as "Frontend" <<system (C4)>>
participant Backend as "BackendManagement" <<system (C4)>>

activate Admin
    Admin -> Frontend : asks to add a new operation type
    activate Frontend
        Frontend --> Admin : asks to insert the details of the operation type
    
    deactivate Frontend
    Admin -> Frontend : inserts the details
    activate Frontend
    
        Frontend-> Backend : POST /operationTypes
        activate Backend
            Frontend <-- Backend : 200 OK
        deactivate Backend
    Frontend --> Admin : displays confirmation message that the operation type was added
    
    deactivate Frontend
    deactivate Admin
@enduml