@startuml

autonumber
participant SYS as "Backend Management" <<system>>

?o-> SYS : POST /api/operation
activate SYS

SYS -> SYS : requestOperation(creatingOperationRequestDTO)
<-- SYS : 201 Created
deactivate SYS


@enduml