@startuml 
autonumber
actor Admin as "Admin"
participant CTRL as "OperationTypesController"
participant SERVICE as "OperationTypeService <<service>>"
database IOperationTypeRepository as "IOperationTypeRepository"

activate Admin

Admin -> CTRL : PUT /api/operationTypes
activate CTRL

CTRL -> SERVICE : disableAsync(OperationTypeId)
activate SERVICE

SERVICE -> IOperationTypeRepository : disableAsync(operationTypeId)

activate IOperationTypeRepository

IOperationTypeRepository -> SERVICE : operationType

deactivate IOperationTypeRepository

SERVICE -> CTRL : operationType

deactivate SERVICE 

CTRL -> Admin : 200 OK

deactivate CTRL 

deactivate Admin
@enduml