@startuml

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system (C4)>>
participant DB as "Database"

Admin -> BE : PUT /api/operationTypes{id}
activate BE

BE -> DB : softDelete(operationTypesId)

activate DB 

DB -> BE : operationType

deactivate DB 

Admin <- BE : 200 OK

deactivate BE

@enduml