@startuml

        UserService --> Builder : create()

        UserService --> Domain : build()

        UserService --> Persistence : repositories()
        activate Persistence

        Persistence --> Factory : create()

        Persistence --> UserService : factory
        deactivate Persistence

        UserService --> Factory : users()
        activate Factory

        Factory --> UserRepository : create()

        Factory --> UserService : userRepository
        deactivate Factory

        UserService --> UserRepository : save(user)

        activate UserRepository

        UserRepository --> UserService : user
        deactivate UserRepository

        UserService --> Controller : user
        deactivate UserService

@enduml