@startuml process-view
autonumber

actor "Admin" as Admin
participant Frontend as "Frontend" <<system (C4)>>
participant BackendManagement as "Backend Management" <<system (C4)>>

activate Admin

    Admin -> Frontend : asks to list operation types

    activate Frontend
        Frontend-> BackendManagement : GET /operationTypes/search
        activate BackendManagement

            Frontend <-- BackendManagement : 200 OK

        deactivate BackendManagement

    Frontend --> Admin : shows operation requests
    
    deactivate Frontend
deactivate Admin

@enduml