@startuml

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system>>
participant DB as "Database"


Admin-> BE : PUT api/staffs/{id}
activate BE

BE -> DB : update staff

activate DB 

DB --> BE : staffProfileUpdated

deactivate DB 

Admin <-- BE : 200 Ok

deactivate BE
 alt add availabilitySlot
            Admin -> BE : POST /api/staffs/{id}/availability-slots
            activate BE
            BE -> DB : add availabilitySlot
            activate DB 
            DB --> BE : addedAvailabilitySlot
            deactivate DB 
                Admin <-- BE : 200 OK
            deactivate BE
        else delete availabilitySlot
            Admin -> BE : DELETE /api/staffs/{id}/availability-slots/hard
            activate BE
            BE -> DB : delete availabilitySlot
            activate DB 
            DB --> BE : deletedAvailabilitySlot
            deactivate DB 
                Admin <-- BE : 200 OK
            deactivate BE
 end

@enduml