@startuml PatientProfileUpdate(level1)

actor Admin as "Admin"
participant SYS as "HealthCare System" <<system (C4)>>

activate Admin 

Admin --> SYS : asks to edit a patient profile 
activate SYS 

SYS --> Admin : confirms the patient profile editing was successful

@enduml