@startuml
'skinparam
skinparam shadowing false

'Entidades
class SwitchJobOpeningPhasesUI <<presentation>> {
- doShow()
- headline()
}
class SwitchJobOpeningPhasesController <<application>>{
- findByJobReference(jobReference: String) : Optional<JobOpeningProcess>
- switchJobOpeningProcessPhase(jobReference: String, advanceOrReturnPhase : int) : JobOpeningProcess
- updateJobOpeningProcess(jobOpeningProcessRepository: JobOpeningProcess) : JobOpeningProcess
}

class AuthorizationService <<service>> {
- ensureAuthenticatedUserHasAnyOf(roles : List<Jobs4uRoles>) : void
}


class RepositoryFactory <<factory>> {
- jobOpenings()
}

class JobOpeningProcessRepository <<repository>> {
- save(jobOpeningProcess :JobOpeningProcess) : JobOpeningProcess
- findByJobReference(jobReference : String) : JobOpeningProcess
}

class JobOpeningProcess <<domain>> {
- switchJobOpeningProcessPhase(jobOpeningProcess:JobOpeningProcess, advanceOrReturnPhase : int) : JobOpeningProcess
}



'Associações
SwitchJobOpeningPhasesUI --> SwitchJobOpeningPhasesController : theController
SwitchJobOpeningPhasesController --> AuthorizationService : authz
SwitchJobOpeningPhasesController --> JobOpeningProcess : jobOpeningProcess
RepositoryFactory --> JobOpeningProcessRepository : jobOpeningProcessRepository
SwitchJobOpeningPhasesController ..> RepositoryFactory
@enduml
