@startuml 
autonumber
actor Admin as "Admin"
participant CTRL as "OperationTypesController"
participant SERVICE as "OperationTypeService <<service>>"
participant OperationTypeDtoList as "OperationTypeDtoList"
database IOperationTypeRepository as "IOperationTypeRepository"

activate Admin

Admin -> CTRL : GET /api/operationtypes/?name=...&specializationId=...&isActive=...
activate CTRL

CTRL -> SERVICE : SearchOperationTypesAsync(searchOperationTypeDto)
activate SERVICE

SERVICE -> IOperationTypeRepository : GetAllAsync()
activate IOperationTypeRepository

IOperationTypeRepository -> SERVICE : operationTypesList 
deactivate IOperationTypeRepository

SERVICE -> SERVICE : Filter operationTypesList \n- Apply Name filter \n- Apply Specialization filter \n- Apply IsActive filter
SERVICE -> OperationTypeDtoList : create()
SERVICE -> CTRL : return filteredOperationTypesList

deactivate SERVICE 

CTRL -> Admin : 200 OK (filteredOperationTypesList)

deactivate CTRL 

deactivate Admin
@enduml
