@startuml process-view
autonumber
skinparam DefaultTextAlignment center

actor Doctor as "Doctor"
participant ComponentUI as "UI Component" <<component (C4)>>
participant Component as "Component" <<component (C4)>>
participant Model as "Model" <<component (C4)>>
participant Service as "Service" <<component (C4)>>
participant HTTP as "HTTP" <<component (C4)>>

participant BackendDataManagement as "Backend Data Management" <<component (C4)>>

activate Doctor

    Doctor -> ComponentUI : asks to update one Operation Request
    activate ComponentUI

        ComponentUI --> Doctor : asks to update data
    
    deactivate ComponentUI

    Doctor -> ComponentUI : update data

    activate ComponentUI

        ComponentUI -> Component : update operation Request
        activate Component

            Component -> Model** : create

            Component -> Service : update operation Request
            activate Service

                Service -> HTTP : put('/operationRequests/{id}')

                activate HTTP
                    HTTP -> BackendDataManagement : PUT /operationRequests/{id}
                    activate BackendDataManagement
                        BackendDataManagement --> HTTP : 200 (operationRequest)
                    deactivate BackendDataManagement
                    
                    HTTP --> Service : operationRequest

                deactivate HTTP

                Service --> Component : operationRequest
            deactivate Service

            Component --> ComponentUI : operationRequest
        deactivate Component

    Doctor <-- ComponentUI : shows updated data
    deactivate ComponentUI

deactivate Doctor

@enduml