@startuml
'skinparam

skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

'Entidades
class ListApplicationsUI <<presentation>> {
- headline()
- doShow()
- elements()
- listApplicationInfo()
- visit()
- listHeader()
}

class ListApplicationsController <<application>>{
- listBackofficeUsers()
- filterBackofficeUsers(users : List<SystemUser>)
}

class AuthorizationService <<service>> {
- ensureAuthenticatedUserHasAnyOf(roles : Set<Role>)
}

class PersistenceContext <<persistence>> {
- repositories()
}

class RepositoryFactory <<factory>> {
- users()
}

class JobApplicationRepository <<repository>> {
- findAll()
}

class ListApplicationFromJobOpeningController <<controller>> {
- listApplications(jobOpening)
- listAllJobOpenings()
}

class JobOpeningRepository <<repository>> {
- findAll()
}

'Associações
ListApplicationsUI --> ListApplicationsController : theController
ListApplicationsController --> AuthorizationService : authz
ListApplicationsController --> JobApplicationService : application svc
JobApplicationService --> PersistenceContext : persistence
PersistenceContext --> RepositoryFactory : factory
RepositoryFactory --> JobApplicationRepository : applicationsRepository
JobApplicationService --> ListApplicationFromJobOpeningController
ListApplicationFromJobOpeningController --> JobOpeningRepository : jobOpeningRepository
@enduml
