@startuml
entity User <<entity>>{
}

class Name <<Value>> {
}

class Email <<Value>> {
}

class PhoneNumber<<Value>>{
}

class Password <<Value>>{}

entity CustomerManager <<entity>>{}

entity Operator <<entity>>{
}

'SystemAdministratorAggregate
entity SystemAdministrator <<entity>>{}


CustomerManager "1" --> "1" User : includes
Operator "1" --> "1" User : includes
SystemAdministrator "1" --> "1" User : includes
User "1" --> "1" Name : has
User "1" --> "1" PhoneNumber : has
User "1" --> "1" Email : has
User "1" --> "1" Password : has

@enduml