@startuml

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system>>
participant DB as "Database"

Admin-> BE : PUT api/operationType/{id}
activate BE

BE -> DB : update operationType

activate DB 

DB -> BE : operationType 

deactivate DB 

Admin <- BE : 200 OK

deactivate BE

@enduml