@startuml

autonumber
actor Admin as "Admin"
participant SYS as "Backend Management" <<system>>

Admin-> SYS : PUT /api/staffs
activate SYS

SYS -> SYS : updateStaff(EditingStaffDTO)
Admin <-- SYS : 200 OK
deactivate SYS


@enduml