@startuml
autonumber
participant Backoffice as "Backoffice User"
participant CTRL as "UsersController"
participant SERVICE as "UserService <<service>>"
participant AUTH0 as "Auth0 API<<external>>"
participant JWT as "JWT Decoder"
participant CONFIG as "Configuration"

activate Backoffice
Backoffice -> CTRL : POST /api/users/reset-password
activate CTRL

CTRL -> SERVICE : ResetPasswordAsync(email)
activate SERVICE

SERVICE -> CONFIG : Get Auth0:Domain, Auth0:ClientId, Auth0:ClientSecret, Auth0:Audience
activate CONFIG
CONFIG --> SERVICE : return values
deactivate CONFIG

SERVICE -> AUTH0 : POST /dbconnections/change_password (email)
activate AUTH0

alt email is valid
    AUTH0 --> SERVICE : reset password email sent
    deactivate AUTH0

    SERVICE -> CTRL : reset password email sent
    deactivate SERVICE
    CTRL --> Backoffice : 201 Email sent

else token is not valid
    activate AUTH0
    activate SERVICE
    AUTH0 --> SERVICE : Exception("User not found")
    deactivate AUTH0

    SERVICE -> CTRL : Exception("User not found")
    deactivate SERVICE
    CTRL <-- Backoffice : 500 Internal Server Error
end

deactivate CTRL
deactivate Backoffice
@enduml