@startuml PatientProfileCreation(level1)

actor Admin as "Admin"
participant SYS as "HealthCare System" <<system (C4)>>

activate Admin 

Admin --> SYS : asks to create a new patient profile 

activate SYS 
SYS --> Admin : displays the form for creating new patient profile

deactivate SYS
Admin --> SYS : submits the form with patient profile details

activate SYS
SYS --> Admin : displays confirmation message that the patient profile was created

deactivate SYS


@enduml