@startuml

autonumber
participant SYS as "Backend Management" <<system (C4)>>

?o-> SYS : POST /api/users/login
activate SYS

SYS -> SYS : login(RequestLoginDto)
<-- SYS : 201 Logged in
deactivate SYS


@enduml