@startuml

autonumber
actor Admin as "Admin"
participant SYS as "Backend Management" <<system>>

Admin-> SYS : PUT /api/operationTypes
activate SYS

SYS -> SYS : updateOperationType(updateOperationTypeDTO)
Admin <-- SYS : 200 OK
deactivate SYS


@enduml