@startuml Patient Profile Creation (level 3 - 2)
autonumber
participant CTRL as "PatientsController"
participant SERVICE as "PatientService <<service>>"
participant PATIENT as "Patient <<domain>>"
participant REPO as "Patient Repository"
participant DTO as "creatingPatientProfileDTO : PatientProfileDTO"

?o-> CTRL : POST /api/patients
activate CTRL

CTRL -> SERVICE : createPatientProfileAsync(creatingPatientProfileDTO)
activate SERVICE

    SERVICE -> PATIENT : create(creatingPatientProfileDTO.firstName, creatingPatientProfileDTO.lastName, creatingPatientProfileDTO.fullName, creatingPatientProfileDTO.birthDate, creatingPatientProfileDTO.gender, creatingPatientProfileDTO.contactInformation, creatingPatientProfileDTO.emergencyContact)
    activate PATIENT

    PATIENT -> SERVICE : patientCreated
    deactivate PATIENT

    SERVICE -> REPO : save(patientCreated)
    activate USERREPO

    REPO -> SERVICE : patientSaved
    deactivate REPO
    activate DTO
    
    SERVICE -> DTO : create(creatingPatientProfileDTO.fullName, creatingPatientProfileDTO.birthDate, creatingPatientProfileDTO.gender, creatingPatientProfileDTO.contactInformation, creatingPatientProfileDTO.emergencyContact)
    
    DTO -> SERVICE : patientProfileDto
    deactivate DTO

    SERVICE -> CTRL : patientProfileDto
    
    <-- CTRL : 201 Patient Profile Created

deactivate SERVICE
deactivate CTRL
@enduml
