@startuml PatientProfileCreation(level3-2)
autonumber
actor Admin as "Admin"
participant CTRL as "PatientsController"
participant SERVICE as "PatientService <<service>>"
participant PATIENT as "Patient <<domain>>"
participant REPO as "PatientRepository"
participant DTO as "creatingPatientDTO : PatientDTO"

Admin-> CTRL : POST /api/patients
activate CTRL

CTRL -> SERVICE : AddAsync(creatingPatientDTO)
activate SERVICE

    SERVICE -> PATIENT : create(creatingPatientDTO.firstName, creatingPatientDTO.lastName, creatingPatientDTO.fullName, creatingPatientProfileDTO.birthDate, creatingPatientProfileDTO.gender, creatingPatientProfileDTO.email, creatingPatientProfileDTO.phoneNumber, creatingPatientProfileDTO.address, creatingPatientProfileDTO.emergencyContact)
    activate PATIENT

    PATIENT --> SERVICE : patientCreated
    deactivate PATIENT

    SERVICE -> REPO : AddAsync(patientCreated)
    activate REPO

    REPO --> SERVICE : patientSaved
    deactivate REPO
    activate DTO
    
    SERVICE -> DTO : create(patient.Id, patient.FirstName, patient.LastName, patient.FullName, patient.BirthDate, patient.Gender.GenderValue, patient.Email, patient.PhoneNumber, patient.Address, patient.EmergencyContact, patient.Active)
    
    DTO --> SERVICE : patientDto
    deactivate DTO

    SERVICE --> CTRL : patientDto
    
    CTRL --> Admin : 201 Patient Profile Created

deactivate SERVICE
deactivate CTRL
@enduml
