@startuml process-view
autonumber
skinparam DefaultTextAlignment center

actor Doctor as "Doctor"
participant ComponentUI as "UI Component" <<component (C4)>>
participant Component as "Component" <<component (C4)>>

participant Service as "Service" <<component (C4)>>
participant HTTP as "HTTP" <<component (C4)>>

participant CTRL as "MedicalRecordController" <<component (C4)>>
participant MedicalRecordService as "MedicalRecordService" <<component (C4)>>
participant MedicalRecordRepo as "MedicalRecordRepo" <<persistence>>
participant MedicalRecord as "MedicalRecord" <<domain>>
activate Doctor

    Doctor -> ComponentUI : selects edit properttie from MedicalRecords List
    activate ComponentUI

        ComponentUI --> Doctor : displays old data and asks to update
    
    deactivate ComponentUI

    Doctor -> ComponentUI : update data and confirm

    activate ComponentUI

        ComponentUI -> Component : update MedicalRecord
        activate Component

            Component -> Service** : create

            Component -> Service : update medicalRecord
            activate Service

                Service -> HTTP : put('/medicalRecords')

                activate HTTP
                    HTTP -> CTRL : PUT /medicalRecords
                    activate CTRL

                    CTRL -> MedicalRecordService : updateAsync(IMedicalRecordDto)
                    
                    activate MedicalRecordService 

                    MedicalRecordService -> MedicalRecordRepo : getByIdAsync(IMedicalRecordDto.id)

                    activate MedicalRecordRepo 

                    MedicalRecordRepo --> MedicalRecordService : MedicalRecord

                    deactivate MedicalRecordRepo

                    MedicalRecordService -> MedicalRecord : ChangeMedicalRecordAllergiesId(IMedicalRecordDto.allergiesId)
                    MedicalRecordService -> MedicalRecord : ChangeMedicalRecordMedicalConditionsId(IMedicalRecordDto.medicalConditionsId)
                    MedicalRecordService -> MedicalRecord : ChangeMedicalRecordNotations(IMedicalRecordDto.notations)

                    MedicalRecordService -> MedicalRecordRepo : save(MedicalRecord)

                    activate MedicalRecordRepo 

                    MedicalRecordRepo --> MedicalRecordService : MedicalRecord

                    deactivate MedicalRecordRepo

                    MedicalRecordService -> MedicalRecordService : toDto(MedicalRecord)

                    MedicalRecordService --> CTRL : IMedicalRecordDto
                    deactivate MedicalRecordService

                    CTRL --> HTTP : 200 (IMedicalRecordDto)

                    deactivate CTRL
                                        
                    HTTP --> Service : IMedicalRecordDto

                deactivate HTTP

                Service --> Component : IMedicalRecordDto
            deactivate Service

            Component --> ComponentUI : IMedicalRecordDto
        deactivate Component

    Doctor <-- ComponentUI : shows updated data
    deactivate ComponentUI

deactivate Doctor

@enduml