@startuml

autonumber
participant SYS as "Backend Management" <<system >>

?o-> SYS : PUT /api/operationTypes
activate SYS

SYS -> SYS : disableOperationType(OperationTypeId)
<-- SYS : 200 OK 
deactivate SYS


@enduml