@startuml

autonumber
participant BE as "Backend Management" <<system (C4)>>
participant DB as "Database"

?o-> BE : POST /api/users

activate BE

BE -> DB : save user

activate DB 

DB --> BE : user 

deactivate DB

<-- BE : 201 Created

deactivate BE

@enduml