@startuml
title Select Interview Model

actor CustomerManager as Actor

participant "SelectInterviewModelUI" as UI
participant "SelectInterviewModelController" as Controller
participant "PersistenceContext" as Persistence
participant "RepositoryFactory" as Factory
participant "JobReference" as JobReferenceDomain
participant "InterviewModel" as InterviewModelDomain
database "JobOpeningRepository" as JobOpeningRepository
database "InterviewModelRepository" as InterviewModelRepository

activate Actor

Actor -> UI: Selects interviewModel
    activate UI

    UI -> Controller: create()

    UI -> Controller : listAllJobOpenings()

        activate Controller

            Controller -> Persistence : create()

            activate Persistence

            Persistence -> Factory : factory()

            deactivate Persistence

            Factory --> Controller : factory


            Controller -> Factory : jobOpenings()

            activate Factory

            Factory --> Controller : JobOpeningRepository

            deactivate Factory

            Controller -> JobOpeningRepository : findAllOpen()

            activate JobOpeningRepository

            JobOpeningRepository --> Controller : jobOpenings

            deactivate JobOpeningRepository

            Controller --> UI : jobOpenings

            deactivate Controller

            UI --> Actor : asks to select a jobOpening

            Actor -> UI : selects the jobOpening

            UI -> Actor : asks to insert the name of the plugin

            Actor -> UI : inserts the name of the plugin

            UI -> Controller : selectInterviewModelToInterview(jobReference,plguinName)

            activate Controller

                Controller -> JobReferenceDomain : create()

                Controller -> InterviewModelDomain : create(jobReference,pluginName)

                Controller -> Factory : interviewModels()

                activate Factory

                Factory --> Controller : interviewModelRepository

                deactivate Factory

                Controller -> InterviewModelRepository : save(interviewModel)

                Controller --> UI : interviewModel

                deactivate Controller

                UI --> Actor : displays a message saying plugin registered successfully
             deactivate UI
             deactivate Actor
@enduml
