@startuml

actor Admin as "Admin"
participant SYS as "HealthCare System" <<system >>

activate Admin 

Admin --> SYS : asks to disable an operation type

activate SYS 

SYS --> Admin : confirms the operation type has been disabled successfully


@enduml