@startuml
actor Admin as "Admin"
participant SYS as "HealthCare System" <<system (C4)>>

activate Admin 

Admin --> SYS : asks to add a new allergy 

activate SYS 
SYS --> Admin : displays the form for adding new allergy
deactivate SYS

Admin --> SYS : submits the form with allergy name, code and description
activate SYS
SYS --> Admin : displays confirmation message that the allergy was added

deactivate SYS

@enduml
