@startuml 
autonumber
actor Doctor as "Doctor"
participant CTRL as "OperationRequestController"
participant SERVICE as "OperationRequestService <<service>>"
database IOperationRequestRepository as "IOperationRequestRepository"
database SpecializationRepository as "SpecializationRepository"


activate Doctor

Doctor -> CTRL : POST /api/operationRequest
activate CTRL

CTRL -> SERVICE : addAsync(creatingOperationRequestDTO)
activate SERVICE

alt specializationValidated = 0 

SERVICE -> SpecializationRepository : getDoctorSpecialization (specializationId,doctorID)

activate SpecializationRepository 

SpecializationRepository -> SERVICE : specializationValidated

deactivate SpecializationRepository

SERVICE -> CTRL : ValueErrorException

CTRL -> Doctor : 406 Not Aceptable
end alt 

SERVICE -> SpecializationRepository : getDoctorSpecialization (specializationId,doctorID)

activate SpecializationRepository 

SpecializationRepository -> SERVICE : specializationValidated

deactivate SpecializationRepository
SERVICE -> IOperationRequestRepository : addAsync(creatingOperationRequestDTO.patientID,creatingOperationRequestDTO.doctorID\n,creatingOperationRequestDTO.operationType,creatingOperationRequestDTO.deadline,\ncreatingOperationRequestDTO.priority)

activate IOperationRequestRepository 

IOperationRequestRepository -> SERVICE : operationRequest
deactivate IOperationRequestRepository


SERVICE -> CTRL : operationRequestDTO

deactivate SERVICE 

CTRL -> Doctor : 201 Created

deactivate CTRL 

deactivate Doctor
@enduml