@startuml logical-view
top to bottom direction
 
interface "API" as API
interface "Auth0" as AUTH0
interface "SMTP Microsoft 365" as SMTP
 
component "Backend Data Management" <<component>> {
  
    portin " " as BEPI
    portout " " as BEPOAUTH0
    portout " " as BEPOSMTP
}
 
BEPI -u- API 
BEPOAUTH0 -l-( AUTH0
BEPOSMTP --( SMTP
 
@enduml