@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Admin as Actor
participant ActivateBackofficeUserUI as UI <<presentation>>
participant ActivateBackofficeUserController as Controller <<application>>
participant AuthorizationService as AuthzService<<service>>
participant UserManagementService as UserService<<service>>
participant SystemUserBuilder as Builder <<builder>>
participant "systemUser:SystemUser" as Domain <<domain>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database UserRepository as Repository <<repository>>

Actor --> UI: Disable backoffice Users
activate Actor
activate UI

    UI -> Controller: create

        UI --> Controller : deactivatedBackofficeUsers()

        activate Controller

        Controller --> AuthzService : ensureAuthenticatedUserHasAnyOf(Jobs4uRoles.POWER_USER,Jobs4uRoles.ADMIN)

        deactivate AuthzService

        Controller --> UserService : deactivatedUsers()

        activate UserService

        UserService --> Persistence : repositories()

        Persistence --> Factory : create()

        Persistence --> UserService : factory
        deactivate Persistence

        UserService --> Factory : users()
        activate Factory

        Factory --> Repository : create()

        Factory --> UserService : userRepository
        deactivate Factory

        UserService --> Repository : findByActive(false)
        activate Repository

        Repository --> UserService : deactivatedUsers
        deactivate Repository

        UserService --> Controller : deactivatedUsers
        deactivate UserService

        activate Controller

        Controller --> Controller : filterBackofficeUsers(deactivatedUsers)

        deactivate Controller

        Controller --> UI : deactivatedBackofficeUsers

        deactivate Controller

        UI--> Actor : display deactivated backoffice users
        deactivate UI

        Actor --> UI : select the user to activate

        activate UI

        UI --> Controller : activateUser(user)

        activate Controller

        Controller --> UserService : activateUser(user)

        activate UserService

        UserService --> Domain : activate(CurrentTime.Calendar.now())

        UserService --> Repository : save(user)

        UserService --> Controller : user
        deactivate UserService

        Controller --> UI : user
        deactivate Controller

        UI --> Actor : display message saying user has been activated

    deactivate UI
    deactivate Actor
    @enduml