@startuml 
autonumber
actor Admin as "Admin"
participant CTRL as "StaffsController"
participant SERVICE as "StaffService <<service>>"
participant StaffProfileDtoList as "StaffProfileDtoList"
database IStaffRepository as "IStaffRepository"

activate Admin
Admin -> CTRL : GET /api/staffs/?fullname=...&specializationId=...&staffEmail=...&staffPhoneNumber...
activate CTRL

CTRL -> SERVICE : SearchStaffsAsync(searchStaffDto)
activate SERVICE

SERVICE -> IStaffRepository : SearchAsync(searchStaffDto)
activate IStaffRepository

IStaffRepository -> IStaffRepository : Filter by fullName,SpecializationId,Email,phoneNumber

IStaffRepository -> SERVICE : filteredStaffs
deactivate IStaffRepository

SERVICE -> StaffProfileDtoList : create()

SERVICE -> CTRL : return filteredStaffsDtoList

deactivate SERVICE 

CTRL -> Admin : 200 OK (filteredStaffsDtoList)

deactivate CTRL 

deactivate Admin
@enduml
