@startuml

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system>>
participant DB as "Database"


Admin -> BE : GET /api/staffs/search{filters}
activate BE

BE -> DB : SearchAsync(name,specialization,status)

activate DB 

DB -> BE : staffs 

deactivate DB

Admin <- BE : 200 OK (staffs)

deactivate BE

@enduml