@startuml StaffProfileDeactivation(level3)

autonumber
skinparam DefaultTextAlignment center
actor Admin as "Admin"
participant ComponentUI as "UI Component" <<component (C4)>>
participant Component as "Component" <<component (C4)>>
participant SRV as "Service" <<component (C4)>>
participant HTTP as "HTTP" <<component (C4)>>

participant BackendManagement as "BackendManagement" <<component (C4)>>

activate Admin

    Admin -> ComponentUI : asks to deactivate a staff profile
    activate ComponentUI

    ComponentUI --> Admin : asks to confirm
    deactivate ComponentUI

    Admin -> ComponentUI : confirms
    activate ComponentUI

        ComponentUI -> Component : deactivate staff
        activate Component

            Component -> SRV : deactivate staff
            activate SRV

                SRV -> HTTP : delete('staffs/{id}')
                activate HTTP

                    HTTP -> BackendManagement : DELETE /staffs/{id}
                    activate BackendManagement

                    BackendManagement --> HTTP : 200 (staffs)
                    deactivate BackendManagement

                HTTP --> SRV : staffs
                deactivate HTTP

            SRV --> Component : staffs
            deactivate SRV

        Component --> ComponentUI : staffs
        deactivate Component

    Admin <-- ComponentUI : shows success message
    deactivate ComponentUI
    
deactivate Admin

@enduml