@startuml

autonumber
actor Admin as "Admin"
participant BE as "Backend Management" <<system>>
participant DB as "Database"

Admin-> BE : PUT api/staffs/{id}
activate BE

BE -> DB : updateAsync(editingStaffDto)

activate DB 

DB -> BE : staffDto

deactivate DB 

Admin <- BE : 200 OK

deactivate BE

@enduml