@startuml 
autonumber
actor Admin as "Admin"
participant CTRL as "StaffsController"
participant SERVICE as "StaffService <<service>>"

database IStaffRepository as "IStaffRepository"


activate Admin

Admin -> CTRL : POST /api/staffs{id}
activate CTRL

CTRL -> SERVICE : updateAsync(editingStaffDto)
activate SERVICE



deactivate IStaffRepository

SERVICE -> IStaffRepository : updateAsync(editingStaffDto.StaffId, editingStaffDto.FirstName, \neditingStaffDto.LastName, editingStaffDto.FullName, editingStaffDto.Email, \neditingStaffDto.PhoneNumber, editingStaffDto.SpecializationId, editingStaffDto.AvailabilitySlots)

activate IStaffRepository

IStaffRepository -> SERVICE : staff

deactivate IStaffRepository


SERVICE -> CTRL : staffDto

deactivate SERVICE 

CTRL -> Admin : 200 OK

deactivate CTRL 

deactivate Admin
@enduml