@startuml process-view
autonumber
skinparam DefaultTextAlignment center
actor Admin as "Admin"
participant ComponentUI as "UI Component" <<component (C4)>>
participant Component as "Component" <<component (C4)>>
participant Service as "Service" <<component (C4)>>
participant HTTP as "HTTP" <<component (C4)>>
participant MedicalConditionController as "MedicalConditionController" <<component (C4)>>
participant MedicalConditionService as "MedicalConditionService" <<component (C4)>>
participant MedicalCondition as "MedicalCondition" <<domain>>
participant MedicalConditionRepo as "MedicalCondition Repository" <<persistence>>

activate Admin

    Admin -> ComponentUI : asks to add new medical condition
    activate ComponentUI

        ComponentUI -> Admin : asks to input data

    deactivate ComponentUI

    Admin -> ComponentUI : input data
    
    activate ComponentUI
    
        ComponentUI -> Component : add new medical condition
        activate Component

            Component -> Service** : create
            
            Component -> Service : add new medical condition
            activate Service

                Service -> HTTP : post('api/medicalConditions')

                activate HTTP
                    HTTP -> MedicalConditionController : POST /medicalConditions

                    activate MedicalConditionController

                    MedicalConditionController -> MedicalConditionService : createMedicalCondition(IMedicalConditionDto.name, IMedicalConditionDto.code,\n IMedicalConditionDto.description, IMedicalCondition.symptoms)

                    activate MedicalConditionService 

                    MedicalConditionService -> MedicalCondition : createMedicalCondition(MedicalConditionProps))

                    MedicalConditionService -> MedicalConditionRepo : save(MedicalConditionProps)

                    activate MedicalConditionRepo

                    MedicalConditionRepo --> MedicalConditionService : medicalCondition

                    deactivate MedicalConditionRepo

                    MedicalConditionService -> MedicalConditionService : toDto(medicalCondition)

                    MedicalConditionService --> MedicalConditionController : IMedicalConditionDto

                    deactivate MedicalConditionService

                    MedicalConditionController --> HTTP : 201 (medicalCondition)

                    deactivate MedicalConditionController

                    HTTP --> Service : medicalCondition

                deactivate HTTP

                Service --> Component : medicalCondition
            deactivate Service

            Component --> ComponentUI : medicalCondition
        deactivate Component

    Admin <-- ComponentUI : shows creation success message
    deactivate ComponentUI

deactivate Admin

@enduml