@startuml

autonumber
actor Doctor as "Doctor"
participant BE as "Backend Management" <<system>>
participant DB as "Database"

Doctor-> BE : POST: api/operationRequests
activate BE

BE -> DB : addAsync(creatingOperationRequestDTO)



activate DB 

DB -> DB : confirms Pacient ID

DB -> DB : confirms doctor specialization

DB -> DB : save operationRequest

activate DB 

DB -> BE : operationRequest 

deactivate DB 

Doctor <- BE : 201 Created

deactivate BE

@enduml