@startuml 
autonumber
actor Doctor as "Doctor"
participant CTRL as "OperationRequestController"
participant SERVICE as "OperationRequestService <<service>>"
participant OperationRequest as "OperationRequest <<domain>>"
participant OperationTypeDTO as "OperationTypeDTO <<domain>>"
database IOperationRequestRepository as "IOperationRequestRepository"
database SpecializationRepository as "SpecializationRepository"


activate Doctor

Doctor -> CTRL : POST /api/operationRequest
activate CTRL

CTRL -> SERVICE : addAsync(creatingOperationRequestDTO)
activate SERVICE

SERVICE -> OperationRequest : create(creatingOperationRequestDTO.patientID,creatingOperationRequestDTO.doctorID\n,creatingOperationRequestDTO.operationType,creatingOperationRequestDTO.deadline,\ncreatingOperationRequestDTO.priority)

activate OperationRequest

OperationRequest -> SERVICE : OperationRequest

deactivate OperationRequest

SERVICE -> IOperationRequestRepository : addAsync(OperationRequest)

activate IOperationRequestRepository

IOperationRequestRepository -> SERVICE : operationRequest

deactivate IOperationRequestRepository

alt specializationValidated = 0 

SERVICE -> SpecializationRepository : getDoctorSpecialization (specializationId,doctorID)

activate SpecializationRepository 

SpecializationRepository -> SERVICE : specializationValidated

deactivate SpecializationRepository

SERVICE -> CTRL : ValueErrorException

CTRL -> Doctor : 406 Not Aceptable
end alt 

SERVICE -> SpecializationRepository : getDoctorSpecialization (specializationId,doctorID)

activate SpecializationRepository 

SpecializationRepository -> SERVICE : specializationValidated

deactivate SpecializationRepository
SERVICE -> OperationRequest : create(patientId, doctorId, operationType, deadline,priority)

activate OperationRequest 

OperationRequest -> SERVICE : operationRequest
deactivate OperationRequest

SERVICE -> IOperationRequestRepository : addAsync(operationRequest)


SERVICE -> OperationTypeDTO : create(operationTypeId,name,anesthesiaTime,surgeryTime,cleaningTime)

activate OperationTypeDTO

OperationTypeDTO -> SERVICE : operationRequestDTO

deactivate OperationTypeDTO

SERVICE -> CTRL : operationRequestDTO

deactivate SERVICE 

CTRL -> Doctor : 201 Created

deactivate CTRL 

deactivate Doctor
@enduml