@startuml
'skinparam
skinparam handwritten true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

'Entidades
class ListBackofficeUsersUI <<presentation>> {
- headline()
- emptyMessage()
- elements()
- elementPrinter()
- elementName()
- listHeader()
}
class ListBackofficeUsersController <<application>>{
- listBackofficeUsers()
- filterBackofficeUsers(users : List<SystemUser>)
}
class AuthorizationService <<service>> {
- ensureAuthenticatedUserHasAnyOf(roles : Set<Role>)

}
class UserManagementService <<service>> {
- allUsers()
}

class PersistenceContext <<persistence>> {
- repositories()

}
class RepositoryFactory <<factory>> {
- users()
}
class UserRepository <<repository>> {
- findAll()
}

'Associações
ListBackofficeUsersUI --> ListBackofficeUsersController : theController
ListBackofficeUsersController --> AuthorizationService : authz
ListBackofficeUsersController --> UserManagementService : user svc
UserManagementService --> PersistenceContext : persistence
PersistenceContext --> RepositoryFactory : factory
RepositoryFactory --> UserRepository : userRepository

@enduml
