@startuml
'skinparam
skinparam handwritten true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

'Entidades
class ActivateBackofficeUserUI <<presentation>> {
- doShow()
- headline()
}
class ActivateBackofficeUserController <<application>>{
- deactivatedUsers()
- filterBackofficeUsers(users : Iterable<SystemUser>)
- activateUser(user : SystemUser)
}
class AuthorizationService <<service>> {
- ensureAuthenticatedUserHasAnyOf(roles : List<Jobs4uRoles>)
}
class UserManagementService <<service>> {
- deactivatedUsers()
- activateUser (user : SystemUser)
}

class PersistenceContext <<persistence>> {
- repositories()
}
class RepositoryFactory <<factory>> {
- users()
}
class UserRepository <<repository>> {
- findByActive(false)
- save(user : SystemUser)
}
class SystemUser <<domain>> {
- activate(time : CurrenTime.Calendar.now())
}
'Associações
ActivateBackofficeUserUI --> ActivateBackofficeUserController : theController
ActivateBackofficeUserController --> AuthorizationService : authz
ActivateBackofficeUserController --> UserManagementService : userSvc
ActivateBackofficeUserController --> SystemUser : activates
UserManagementService --> PersistenceContext : persistence
PersistenceContext --> RepositoryFactory : factory
RepositoryFactory --> UserRepository : userRepository

@enduml
