@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Admin as Actor
participant ListBackofficeUsersUI as UI <<presentation>>
participant ListBackofficeUsersController as Controller <<application>>
participant AuthorizationService as AuthzService<<service>>
participant UserManagementService as UserService<<service>>
participant SystemUserBuilder as Builder <<builder>>
participant "systemUser:SystemUser" as Domain <<domain>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database UserRepository as Repository <<repository>>

Actor --> UI: List backoffice users
activate Actor
activate UI

    UI -> Controller: create

        UI --> Controller : backofficeUsers()

        activate Controller

        Controller --> AuthzService : ensureAuthenticatedUserHasAnyOf(Jobs4uRoles.POWER_USER,Jobs4uRoles.ADMIN)

        deactivate AuthzService

        Controller --> UserService : allUsers()

        activate UserService

        UserService --> Persistence : repositories()

        Persistence --> Factory : create()

        Persistence --> UserService : factory
        deactivate Persistence

        UserService --> Factory : users()
        activate Factory

        Factory --> Repository : create()

        Factory --> UserService : userRepository
        deactivate Factory

        UserService --> Repository : findAll()
        activate Repository

        Repository --> UserService : allUsers
        deactivate Repository

        UserService --> Controller : allUsers
        deactivate UserService

        activate Controller

        Controller --> Controller : filterBackofficeUsers(allUsers)
        deactivate Controller

        Controller --> UI : backofficeUsers

        deactivate Controller

    UI--> Actor : display backoffice Users

deactivate UI
deactivate Actor
@enduml