@startuml

title System Use Case Diagram
skinparam packageStyle rectangle


actor "Customer Manager" as CustomerManager
actor "Language Engineer" as LanguageEngineer
actor "Operator" as Operator
actor "Administrator" as Administrator
actor "Project Manager" as ProjectManager
actor "Candidate" as Candidate
actor "Customer" as Customer

left to right direction

usecase "Display Candidate Information" as DisplayCandidateInformation
usecase "List Applications" as ListApplications
usecase "Generate Interview File" as GenerateInterviewFile
usecase "Disable BackOffice Users" as DisableBackOfficeUsers
usecase "Enable BackOffice Users" as EnableBackOfficeUsers
usecase "Register BackOffice Users" as RegisterBackOfficeUsers
usecase "List Users From BackOffice" as ListUsersFromBackOffice
usecase "Register Application" as RegisterApplication
usecase "Display candidate Info" as DisplayCandidateInfo
usecase "Register Candidate" as RegisterCandidate
usecase "Register Customer" as RegisterCustomer
usecase "Register Job Opening" as RegisterJobOpening
usecase "Setup Job Opening Process" as SetupJobOpeningProcess
usecase "Select Interview Model" as SelectInterviewModel
usecase "Select Requirements for Job Opening" as SelectRequirementsforJobOpening
usecase "Deploy and Configure Plugin" as DeployandConfigurePlugin
usecase "Authentication Services" as AuthenticationServices
usecase "Authorizarion Services" as AuthorizarionServices
usecase "Publish Rank results" as PublishRankResults
usecase "Notified when Application Status change" as NotifiedApplicationStatus
usecase "List all applications " as ListAllApplications
usecase "List all job openings" as ListAllJobOpenings
usecase "Rank candidate" as RankCandidates
usecase "Notify Candidates about verification process" as NotifyCandidatesVerificationProcess
usecase "Evaluate grades of a interview" as EvaluateGrades
usecase "Upload Candidate answers" as UploadAnswers
usecase "Upload Candidate requirements file" as UploadRequirements
usecase "Get an Ordered list of candidates by interview grade" as OrderedCandidateList
usecase "Open or close phases of a job opening" as OpenClosePhase
usecase "Execute verification process of requirements" as ExecuteVerificationProcess
usecase "Get top 20 words of candidate files" as GetTop20


LanguageEngineer --> DisplayCandidateInformation
LanguageEngineer --> GenerateInterviewFile
LanguageEngineer --> DeployandConfigurePlugin
LanguageEngineer --> SelectRequirementsforJobOpening
LanguageEngineer --> SelectInterviewModel

ProjectManager --> AuthenticationServices
ProjectManager --> AuthorizarionServices

CustomerManager --> RegisterJobOpening
CustomerManager --> SetupJobOpeningProcess
CustomerManager --> DisplayCandidateInfo
CustomerManager --> ListApplications
CustomerManager --> RegisterCustomer
CustomerManager --> PublishRankResults
CustomerManager --> RankCandidates
CustomerManager --> NotifyCandidatesVerificationProcess
CustomerManager --> EvaluateGrades
CustomerManager --> UploadAnswers
CustomerManager --> OrderedCandidateList
CustomerManager --> OpenClosePhase
CustomerManager --> ExecuteVerificationProcess
CustomerManager --> GetTop20


Administrator --> DisableBackOfficeUsers
Administrator --> EnableBackOfficeUsers
Administrator --> RegisterBackOfficeUsers
Administrator --> ListUsersFromBackOffice

Operator --> RegisterApplication
Operator --> RegisterCandidate
Operator --> UploadRequirements

Candidate --> NotifiedApplicationStatus
Candidate --> ListAllApplications

Customer --> ListAllJobOpenings



@enduml