@startuml Patient Profile Delete (level 1)

actor Admin as "Admin"
participant SYS as "HealthCare System" <<system (C4)>>

activate Admin 

Admin --> SYS : asks to delete a patient profile

activate SYS 

SYS -> Admin : Confirm patient profile deletion

deactivate SYS
deactivate Admin


@enduml