@startuml

autonumber
Actor Doctor as "Doctor"
participant SYS as "Backend Management" <<system>>

Doctor-> SYS : DELETE /{id}/delete
activate SYS

SYS -> SYS : removeOperation(operationId)
Doctor<-- SYS : 200 Ok
deactivate SYS


@enduml