@startuml AddAppointment(level1)

actor Doctor as "Doctor"
participant SYS as "HealthCare System" <<system (C4)>>

activate Doctor 

Doctor --> SYS : asks to add a new appointment 

activate SYS 
SYS --> Doctor : displays the form for adding new appointment
deactivate SYS

Doctor --> SYS : submits the form with appointment data
activate SYS
SYS --> Doctor : displays confirmation message that the appointment was added

deactivate SYS

@enduml
