@startuml 
autonumber
actor Patient as PATIENT
participant CTRL as "UsersController"
participant SERVICE as "UserService <<service>>"
participant User as "User <<domain>>"
participant Patient as "Patient <<domain>>"
participant USERREPO as "UserRepository"
participant PATIENTREPO as "Patient Repository"
participant DTO as "creatingPatientUserDTO : PatientUserDTO"

activate PATIENT
PATIENT-> CTRL : POST /api/users/patients
activate CTRL

CTRL -> SERVICE : createUserPacientAsync(creatingUserDTO)
activate SERVICE

SERVICE -> PATIENTREPO : GetByEmailAsync(creatingUserDTO.email)
activate PATIENTREPO
alt Patient not found (patient == null)

    activate PATIENTREPO

    PATIENTREPO -> SERVICE : 404 NotFound
    
    deactivate PATIENTREPO

    SERVICE -> CTRL : 404 NotFound

else Patient found (patient != null)
    PATIENTREPO -> SERVICE : patient
    deactivate PATIENTREPO

    SERVICE -> User : create(creatingPatientUserDTO.email, creatingPatientUserDTO.username, creatingPatientUserDTO.password)
    activate User

    User -> SERVICE : patientUserCreated
    deactivate User

    SERVICE -> Patient : setUser(userCreated)
    SERVICE -> USERREPO : save(userCreated)
    activate USERREPO

    USERREPO -> SERVICE : userSaved
    deactivate USERREPO

    SERVICE -> PATIENTREPO : save(patient)
    activate PATIENTREPO

    PATIENTREPO -> SERVICE : patientSaved
    deactivate PATIENTREPO

    SERVICE -> DTO : create(creatingPatientUserDTO.email,creatingPatientUserDTO.username) 

    activate DTO

    DTO -> SERVICE : userPatientDTO

    deactivate DTO 

    SERVICE -> CTRL : userDTO

    deactivate SERVICE
    
    PATIENT <-- CTRL : 201 User created and user information

else 
end
deactivate CTRL
deactivate PATIENT

@enduml
