@startuml 
autonumber
participant CTRL as "UsersController"
participant SERVICE as "UserService <<service>>"
participant User as "User <<domain>>"
participant Patient as "Patient <<domain>>"
participant USERREPO as "UserRepository"
participant PATIENTREPO as "Patient Repository"
participant DTO as "creatingUserDTO : UserDTO"

?o-> CTRL : POST /api/users/patients
activate CTRL

CTRL -> SERVICE : createUserPacientAsync(creatingUserDTO)
activate SERVICE

SERVICE -> PATIENTREPO : GetByEmailAsync(creatingUserDTO.email)
activate PATIENTREPO
alt Patient not found (patient == null)

    activate PATIENTREPO

    PATIENTREPO -> SERVICE : 404 NotFound
    
    deactivate PATIENTREPO

    SERVICE -> CTRL : 404 NotFound

else Patient found (patient != null)
    PATIENTREPO -> SERVICE : patient
    deactivate PATIENTREPO

    SERVICE -> User : create(creatingUserDTO.email, creatingUserDTO.username, creatingUserDTO.role)
    activate User

    User -> SERVICE : userCreated
    deactivate User

    SERVICE -> Patient : setUser(userCreated)
    SERVICE -> USERREPO : save(userCreated)
    activate USERREPO

    USERREPO -> SERVICE : userSaved
    deactivate USERREPO

    SERVICE -> PATIENTREPO : save(patient)
    activate PATIENTREPO

    PATIENTREPO -> SERVICE : patientSaved
    deactivate PATIENTREPO

    SERVICE -> CTRL : userDTO
    
    <-- CTRL : 201 User created

else 
end

deactivate SERVICE
deactivate CTRL
@enduml
