@startuml

skinparam packageStyle rectangle

package InterviewModelAggregate {
  entity InterviewModel<<root>> <<entity>> {}
  class InterviewModelPlugin <<Value>>{}
}

package ApplicationAggregate {
  entity Application<<entity>> <<root>>  {}
  class ApplicationDate <<Value>> {}
  enum ApplicationStatus <<Value>> {
    Approved
    Denied
    WaitingInterview
    InProgress
  }
}

package ValidationService {
  entity ANTLRValidator <<service>> {}
}

package CandidateAggregate{
  entity Candidate <<entity>> <<root>> {}
  class PhoneNumber<<Value>>{}
}

package InterviewAggregate {
  class Interview <<entity>><<root>>{}
  class Score<<value>>{}
  class JustificationText<<value>>{}
  class InterviewDate<<value>>{}
  class InterviewTime<<value>>{}
}

package UserAggregate {
  entity User <<root>> <<entity>>{}
  class Name <<Value>> {}
  class Email <<Value>> {}
  class Password <<Value>>{}
}


Interview "1" --> "1" Score : generates
Interview "1" --> "1" JustificationText
Interview "1" --> "1" InterviewDate
Interview "1" --> "1" InterviewTime

InterviewModel "1" --> "1" InterviewModelPlugin : has
Interview "1" --> "1" InterviewModel : follows

ANTLRValidator --> Interview : validates

Candidate "1" --> "1" PhoneNumber : has
Candidate "1" --> "1" User : includes
User "1" --> "1" Name : has
User "1" --> "1" Email : has
User "1" --> "1" Password : has

Application "1" --> "1" ApplicationDate
Application "1" --> "1" Interview
Application "1" --> "1" ApplicationStatus
Application "1" --> "1" Candidate : belongs to



}


 @enduml