name: .NET Build, Test & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./dddnetcore/dddnetcore.csproj

    - name: Build
      run: dotnet build ./dddnetcore/dddnetcore.csproj --no-restore

    - name: Test
      run: dotnet test ./dddnetcore/dddnetcore.csproj --no-build --verbosity normal

    - name: Publish for deployment
      run: dotnet publish ./dddnetcore/dddnetcore.csproj -c Release -o ./publish/dddnetcore

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-build
        path: ./publish/dddnetcore

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Transfer Backend to Remote Server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: ./dddnetcore/*
        target: ~/apps/healthcare

    - name: Deploy Backend
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          ~/apps/healthcare/deploy.sh

