@startuml

autonumber
participant FE as "Frontend" <<system(C4)>>
participant BE as "Backend Management" <<system (C4)>>
participant DB as "Database"

activate FE
FE-> BE : POST /api/operationTypes
activate BE

BE -> DB : get specialization

activate DB 

DB -> BE : specialization

deactivate DB 

BE -> DB : save operationType

activate DB 

DB -> BE : operationType 

deactivate DB 

FE <- BE : 201 Created

deactivate BE
deactivate FE

@enduml